claw-project/claw-compiler

- scripts/pack_release.sh
> Release management

- documentation/developer/developers_guide.bib
- documentation/developer/developers_guide.tex
> Developer's guide v1.0

- omni-cx2x/src/cx2x/translator/transformation/loop/LoopFusion.java
- omni-cx2x/src/cx2x/xcodeml/helper/XnodeUtil.java
- omni-cx2x/src/cx2x/xcodeml/xnode/Xnode.java
- test/loops/CMakeLists.txt
- test/loops/fusion8/CMakeLists.txt
- test/loops/fusion8/original_code.f90
- test/loops/fusion8/reference.f90
> Additional check for the loop-fusion directive

- CMakeLists.txt
- driver/libexec/claw_f_lib.sh.in
> Add commit hash of the OMNI Compiler submodule in the version message

- .gitignore
- omni-cx2x/src/CMakeLists.txt
- omni-cx2x/src/build.xml
- omni-cx2x/src/cx2x/ClawVersion.java.in
- omni-cx2x/src/cx2x/Cx2x.java
- omni-cx2x/src/cx2x/translator/config/Configuration.java
> Check version

- driver/bin/clawfc.in
- driver/etc/claw-default.xml
- driver/libexec/claw_f_lib.sh.in
- omni-cx2x/src/cx2x/Cx2x.java
- omni-cx2x/src/cx2x/translator/ClawXcodeMlTranslator.java
- omni-cx2x/src/cx2x/translator/config/Configuration.java
- omni-cx2x/src/cx2x/translator/report/ClawTransformationReport.java
- omni-cx2x/src/cx2x/translator/transformer/ClawTransformer.java
- omni-cx2x/src/cx2x/xcodeml/transformation/DependentTransformationGroup.java
- omni-cx2x/src/cx2x/xcodeml/transformation/IndependentTransformationGroup.java
- omni-cx2x/src/cx2x/xcodeml/transformation/TransformationGroup.java
- omni-cx2x/unittest/cx2x/translator/common/analysis/dependence/DependenceAnalysisTest.java
- Report generation with information of current transformation
- Transformation orders and count
> CLAW Transformation Report - Main information

- driver/bin/clawfc.in
- Update to rev. 37d6c43c77e82f8ff844e45062fb51d8f63c9d31
This will include fix for: 
- `VALUE` parameter
- `iso_fortran_env` module
- Cray >=8.5
> Update OMNI Compiler submodule

- driver/bin/clawfc.in
- driver/libexec/claw_f_lib.sh.in
- test/driver/CMakeLists.txt
- test/driver/backslash_preprocessor/CMakeLists.txt
- test/driver/backslash_preprocessor/original_code.f90
- test/driver/backslash_preprocessor/reference.f90
> Workaround the backslash preprocessor problem

- driver/bin/clawfc.in
- driver/etc/claw_f.conf.in
- driver/libexec/claw_f_lib.sh.in
- scripts/offline.sh
- scripts/pack_release.sh
- scripts/run.shellcheck.sh
- Add proper headers to bash files
- Unify variable names as lower-case
> Bash code style (part1)

- .travis.yml
- driver/bin/clawfc.in
- driver/libexec/claw_f_lib.sh.in
- scripts/run.shellcheck.sh
- test/driver/CMakeLists.txt
- test/driver/lib/test.claw_f_lib.sh
> Remove dependency to omni_common_lib.sh from driver

- driver/libexec/claw_f_lib.sh.in
> Redirect output when resolving dependency

- test/CMakeLists.txt
- test/omni/CMakeLists.txt
- test/omni/constant_kind/CMakeLists.txt
- test/omni/constant_kind/main.f90
- test/omni/constant_kind/mo_column.f90
- test/omni/constant_kind/reference_cpu.f90
- test/omni/constant_kind/reference_gpu.f90
- test/omni/constant_kind/reference_main_cpu.f90
- test/omni/constant_kind/reference_main_gpu.f90
Fix the issue with KIND specifier
> Update OMNI dependencies for issue 177

- driver/bin/clawfc.in
- test/claw/directive/CMakeLists.txt
- test/claw/directive/compile-guard3/CMakeLists.txt
- test/claw/directive/compile-guard3/original_code.f90
- test/claw/directive/compile-guard3/reference.f90
- test/claw/directive/compile-guard4/CMakeLists.txt
- test/claw/directive/compile-guard4/original_code.f90
- test/claw/directive/compile-guard4/reference.f90
> Do not skip file with compile guard but no CLAW directives 

- README.dev.md
- omni-cx2x/config/claw_code_style_idea.xml
- omni-cx2x/src/cx2x/translator/transformation/loop/LoopFusion.java
- omni-cx2x/src/cx2x/xcodeml/helper/XnodeUtil.java
- omni-cx2x/src/cx2x/xcodeml/xnode/Xnode.java
- test/loops/CMakeLists.txt
- test/loops/fusion11/reference.f90
- test/loops/fusion12/CMakeLists.txt
- test/loops/fusion12/original_code.f90
- test/loops/fusion12/reference.f90
- test/loops/fusion13/CMakeLists.txt
- test/loops/fusion13/original_code.f90
- test/loops/fusion13/reference.f90
- Delete directives in the previous/next siblings if they correspond to a certain criteria.
> Loop fusion with other directive (delete obsolete OpenACC or OpenMP directives) #215

- driver/bin/clawfc.in
- driver/libexec/claw_f_lib.sh.in
- test/base_test.cmake
- test/module_test.cmake
- --debug is for transformation information
- --debug-omni is for driver/OMNI debugging
#199
> Update behavior of --debug/--debug-omni flags

- scripts/git_hooks/pre-commit
> Update pre-commit hooks

- .gitmodules
Test a version of OMNI Compiler with fix that are still waiting to be merged. 
https://github.com/omni-compiler/omni-compiler/issues/190
https://github.com/omni-compiler/omni-compiler/issues/191
https://github.com/omni-compiler/omni-compiler/issues/192
https://github.com/omni-compiler/omni-compiler/pull/193
https://github.com/omni-compiler/omni-compiler/pull/195
https://github.com/omni-compiler/omni-compiler/pull/196
> Test forked omni version

- omni-cx2x/src/cx2x/translator/ClawTranslator.java
- omni-cx2x/src/cx2x/translator/ClawTranslatorDriver.java
- omni-cx2x/src/cx2x/translator/language/helper/TransformationHelper.java
- omni-cx2x/src/cx2x/translator/transformation/claw/parallelize/Parallelize.java
- omni-cx2x/src/cx2x/translator/transformation/loop/ArrayTransform.java
- omni-cx2x/src/cx2x/translator/transformation/openacc/OpenAccContinuation.java
- omni-cx2x/src/cx2x/xcodeml/helper/XnodeUtil.java
- omni-cx2x/src/cx2x/xcodeml/transformation/Transformation.java
- omni-cx2x/src/cx2x/xcodeml/transformation/Translator.java
- test/claw/abstraction/CMakeLists.txt
- test/claw/abstraction/abstraction30/CMakeLists.txt
- test/claw/abstraction/abstraction30/original_code.f90
- test/failure_test.cmake
> Detect unsupported statements based on target/directive

- omni-cx2x/src/cx2x/translator/common/NestedDoStatement.java
- omni-cx2x/src/cx2x/translator/common/Utility.java
- omni-cx2x/src/cx2x/translator/language/base/ClawLanguage.java
- omni-cx2x/src/cx2x/translator/language/helper/TransformationHelper.java
- omni-cx2x/src/cx2x/translator/language/helper/accelerator/AcceleratorGenerator.java
- omni-cx2x/src/cx2x/translator/language/helper/accelerator/AcceleratorHelper.java
- omni-cx2x/src/cx2x/translator/language/helper/accelerator/AcceleratorNone.java
- omni-cx2x/src/cx2x/translator/language/helper/accelerator/OpenAcc.java
- omni-cx2x/src/cx2x/translator/language/helper/accelerator/OpenMp.java
- omni-cx2x/src/cx2x/translator/language/parser/Claw.g4
- omni-cx2x/src/cx2x/translator/transformation/claw/parallelize/Parallelize.java
- omni-cx2x/src/cx2x/translator/transformation/claw/parallelize/ParallelizeForward.java
- omni-cx2x/src/cx2x/translator/transformation/loop/LoopHoist.java
- omni-cx2x/src/cx2x/translator/transformation/openacc/OpenAccContinuation.java
- omni-cx2x/src/cx2x/xcodeml/helper/NestedDoStatement.java
- omni-cx2x/src/cx2x/xcodeml/helper/XnodeUtil.java
- omni-cx2x/src/cx2x/xcodeml/language/DimensionDefinition.java
- omni-cx2x/unittest/cx2x/translator/language/ClawLanguageTest.java
- omni-cx2x/unittest/cx2x/translator/misc/UtilityTest.java
- omni-cx2x/unittest/cx2x/xcodeml/xnode/XnodeUtilTest.java
- test/claw/abstraction/CMakeLists.txt
- test/claw/abstraction/abstraction17/reference_gpu.f90
- test/claw/abstraction/abstraction32/CMakeLists.txt
- test/claw/abstraction/abstraction32/main.f90
- test/claw/abstraction/abstraction32/mo_column.f90
- test/claw/abstraction/abstraction32/reference_cpu.f90
- test/claw/abstraction/abstraction32/reference_gpu.f90
- test/claw/abstraction/abstraction32/reference_main_cpu.f90
- test/claw/abstraction/abstraction32/reference_main_gpu.f90
- Allow to skip unsupported statement in the preamble and epilogue of the the function body
#285
> Adapt parallel region start and end for GPU

- omni-cx2x/src/claw/tatsu/primitive/Pragma.java
- omni-cx2x/src/claw/tatsu/xcodeml/xnode/common/Xnode.java
- omni-cx2x/src/claw/wani/x2t/translator/ClawTranslatorDriver.java
- test/claw/abstraction/abstraction4/CMakeLists.txt
**READY**
Update to the version 1.2.2 of the OMNI Compiler.
> Update submodule to version 1.2.2

- compiler/cray.cmake
- compiler/gnu.cmake
- compiler/pgi.cmake
- driver/bin/clawfc.in
- driver/libexec/claw_f_lib.sh.in
> Add specific compiler macro

- omni-cx2x/src/claw/tatsu/directive/generator/DirectiveGenerator.java
- omni-cx2x/src/claw/tatsu/xcodeml/xnode/fortran/FfunctionType.java
**REVIEW**
Avoid creation of empty instance
-
> Avoid creation of empty instance

- cx2t/src/claw/wani/transformation/sca/ParallelizeForward.java
**REVIEW**
Check whether a parent module exists or not
> [SCA] Secure forward anaylsis

- .travis.yml
**REVIEW**
- Send notification in the `travis-ci` channel
> New travis CI settings to send notification on the new slack workspace

- cmake/omni_compiler.cmake
**REVIEW**
* Update Cray custom command to not output xcodeml on stdout.
> Do not output XcodeML with generating XcodeML module file

- properties.cmake
**REVIEW**
* Declaration of `CLAW_XMOD_GENERIC` done too early.
> Fix declaration of CLAW_XMOD_GENERIC

- cx2t/src/claw/tatsu/TatsuConstant.java
- cx2t/src/claw/tatsu/common/Target.java
- cx2t/src/claw/wani/transformation/sca/Parallelize.java
- cx2t/unittest/claw/wani/language/language/ClawEnumTest.java
**REVIEW**
* Add a specific target for ARM
> Add ARM target

- test/claw/abstraction/abstraction32/main.f90
- test/claw/abstraction/abstraction32/mo_column.f90
- test/claw/abstraction/abstraction32/reference_cpu.f90
- test/claw/abstraction/abstraction32/reference_gpu.f90
- test/claw/abstraction/abstraction32/reference_main_cpu.f90
- test/claw/abstraction/abstraction32/reference_main_gpu.f90
**REVIEW**
* Add scalar var that should be promoted.
> Update test abstraction32 for scalar promotion

- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/primitive/Body.java
- cx2t/src/claw/tatsu/xcodeml/xnode/XnodeUtil.java
- cx2t/src/claw/wani/transformation/sca/Parallelize.java
- test/claw/abstraction/abstraction28/main.f90
- test/claw/abstraction/abstraction28/mo_column.f90
- test/claw/abstraction/abstraction28/reference_cpu.f90
- test/claw/abstraction/abstraction28/reference_gpu.f90
- test/claw/abstraction/abstraction28/reference_main_cpu.f90
- test/claw/abstraction/abstraction28/reference_main_gpu.f90
**REVIEW**
* Fix how to gather of arguments for `allocatable`
> SCA - OpenACC data region generation fix

- .travis.yml
**REVIEW**
* Add GCC 6 and 7 in the matrix
> Add GCC 6 and 7

- cx2t/src/claw/tatsu/primitive/Field.java
- cx2t/src/claw/tatsu/xcodeml/abstraction/PromotionInfo.java
- cx2t/src/claw/wani/transformation/sca/ParallelizeForward.java
**REVIEW**
* Avoid multiple adaptations of the array references.
Issue #355
> Fix multiple adapation of references

- cx2t/src/claw/wani/transformation/sca/Parallelize.java
**REVIEW**
* Add more control to flag assignement requiring do statement insertion. 
Issue #355
> Control that flagged assignement are not already nested

- cx2t/src/claw/ClawX2T.java
- cx2t/src/claw/wani/x2t/translator/ClawPythonTranslatorDriver.java
- cx2t/src/claw/wani/x2t/translator/ClawTranslatorDriver.java
**REVIEW**
See #364. Basically is a precursor to adding support for Python-defined transformations.
> 2nd attempt at adding script argument and re-factoring.

- cx2t/src/claw/ClawX2T.java
- cx2t/src/claw/wani/x2t/translator/ClawPythonTranslatorDriver.java
**REVIEW**
* Just applied reformat from IntelliJ
> Format + cleanup imports

- cx2t/src/claw/wani/x2t/translator/ClawTranslatorDriver.java
**REVIEW**
* Lower accessibility
> lower accessibility of variables and ctor

- README.dev.md
- documentation/developer/code/MyFirstTransformation.java
- documentation/developer/code/claw-default.xml
- documentation/developer/code/claw-internal-set.xml
- documentation/developer/code/clawp.g4
- documentation/developer/code/external_config.xml
- documentation/developer/guide_claw_parser.tex
- documentation/manual/claw_fortran_compiler.tex
- driver/bin/clawfc.in
- driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Rename old reference of `cx2x` to `cx2t`
> Update old references to cx2x

- cx2t/src/claw/tatsu/TatsuConstant.java
- cx2t/src/claw/tatsu/common/CompilerDirective.java
- cx2t/unittest/claw/tatsu/common/CompilerDirectiveTest.java
- driver/libexec/claw_f_lib.sh.in
**REVIEW**
* `acc` and `omp` accepted as options
> Accept short version of directive as option

- compiler/intel.cmake
- test/claw_reference_test.cmake
**REVIEW**
* Support the use of the Intel compiler in the CLAW workflow (preprocessing)
> Intel compiler support complete

- CHANGELOG.md
- driver/bin/clawfc.in
- driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Clean up the temp directory if exiting the driver
> Driver clean up on exit

- CHANGELOG.md
- CMakeLists.txt
- cx2t/src/claw/tatsu/common/Utility.java
- cx2t/src/claw/wani/transformation/sca/Parallelize.java
- test/claw/sca/sca36/mo_column.f90
- test/claw/sca/sca36/reference_cpu.f90
- test/claw/sca/sca36/reference_gpu.f90
**REVIEW**
* Fix problem in the CPU backend when condition relies on promoted variables.
> Fix missing do statement with condition

- cx2t/src/claw/wani/transformation/sca/Parallelize.java
**REVIEW**
* Avoid possible nested do statements to be inserted sharing the same induction var
> [SCA] Tweak do statement location insertion

- cx2t/src/claw/wani/transformation/sca/Parallelize.java
**REVIEW**
* Cleanup warning message
> Remove duplicate warning keyword

- cx2t/src/claw/ClawX2T.java
- cx2t/src/claw/shenron/translator/Translator.java
- cx2t/src/claw/tatsu/common/Context.java
- cx2t/src/claw/tatsu/primitive/Module.java
- cx2t/src/claw/tatsu/xcodeml/module/ModuleCache.java
- cx2t/src/claw/wani/transformation/sca/Parallelize.java
- cx2t/src/claw/wani/transformation/sca/ParallelizeForward.java
- cx2t/src/claw/wani/x2t/translator/ClawTranslator.java
- cx2t/src/claw/wani/x2t/translator/ClawTranslatorDriver.java
**REVIEW**
* Move `ModuleCache` to the `Context`
* Remove dependency to `exc.xcodeml.XcodeMLtools_Fmod`
> Remove dependency to exc.xcodeml.XcodeMLtools_Fmod

- cx2t/src/claw/wani/transformation/sca/Parallelize.java
**REVIEW**
* Avoid double flagging of condition to insert do statements
> [SCA] Avoid nested do statements generation in condition check

- driver/bin/clawfc.in
- driver/libexec/claw_f_lib.sh.in
- scripts/check_license
- scripts/pack_release
**REVIEW**
* Check scripts with new shellcheck version
> [Infrastructure] Fix new shellcheck checks advices

- properties.cmake
> Update OMNI related install path

- test/claw/sca/sca16/reference_extra_cpu.f90
- test/claw/sca/sca16/reference_extra_gpu.f90
**REVIEW**
* Update OMNI Compiler submodule to omni-compiler/xcodeml-tools@843cc4b1aaad39886f297204ef927116e8a75df1
> Update OMNI Compiler hash 843cc4b1aaad39886f297204ef927116e8a75df1

- .travis.yml
- CMakeLists.txt
- cmake/omni_compiler.cmake
- cx2t/CMakeLists.txt
- cx2t/src/CMakeLists.txt
- cx2t/unittest/CMakeLists.txt
- modules/CMakeLists.txt
- test/claw_reference_test.cmake
**REVIEW**
* Update cmake to be able to work with multiple threads
* Update travis file
> Update cmake for parallel execution

- cx2t/src/claw/tatsu/primitive/Xmod.java
- cx2t/src/claw/tatsu/xcodeml/exception/IllegalDirectiveException.java
- cx2t/src/claw/tatsu/xcodeml/module/ModuleCache.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FfunctionDefinition.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FortranModule.java
- cx2t/src/claw/wani/transformation/sca/Parallelize.java
- cx2t/src/claw/wani/transformation/sca/ParallelizeForward.java
- cx2t/unittest/claw/tatsu/primitive/XmodTest.java
**REVIEW**
* Rename Module class to Xmod
> Rename Module to Xmod for Java 10 support

- driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Fix error message
> Fix error message

- driver/libexec/claw_f_lib.sh.in
**REVIEW**
* `mapfile` is not supported on daint and on OS X so remove this feature
> Remove mapfile as it fails on many paltform

- cx2t/src/claw/ClawX2T.java
> Fix configuration file error message

- cx2t/src/claw/tatsu/xcodeml/backend/OmniBackendDriver.java
- test/claw/sca/sca16/reference_extra_cpu.f90
- test/claw/sca/sca16/reference_extra_gpu.f90
**REVIEW**
* Update OMNI Compiler submodule to omni-compiler/xcodeml-tools@43933b0b3fca010b16ee94f2bcc3ff625ca3ac92
> Update OMNI Compiler submodule 43933b0

- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/directive/generator/OpenAcc.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FortranType.java
- test/claw/sca/CMakeLists.txt
- test/claw/sca/sca34/reference_gpu.f90
- test/claw/sca/sca35/reference_gpu.f90
- test/claw/sca/sca37/main.f90
- test/claw/sca/sca37/mo_column.f90
- test/claw/sca/sca37/reference_cpu.f90
- test/claw/sca/sca37/reference_gpu.f90
- test/claw/sca/sca37/reference_main_cpu.f90
- test/claw/sca/sca37/reference_main_gpu.f90
**REVIEW**
* In some cases, `!$acc loop seq` was generated at the wrong place.
> [SCA/OpenACC] Fix mixed order directive generation

- INSTALL.md
hi guys!
just a single sign to make the link work ;-)
hth
try2
> fix type in link to omni website

- README.dev.md
**REVIEW**
* Update OMNI Compiler submodule to omni-compiler/xcodeml-tools@2b72cd9fc9c6133bf9f806d3b7fc5a369265d605
> Update OMNI Compiler to 2b72cd9fc9c6133bf9f806d3b7fc5a369265d605

- cx2t/src/claw/tatsu/primitive/Pragma.java
- cx2t/unittest/claw/tatsu/primitive/PragmaTest.java
- test/openacc/CMakeLists.txt
- test/openacc/primitive4/original_code.f90
- test/openacc/primitive4/reference.f90
**REVIEW**
* Fix empty first pragma generated with primitive clause.
Issue #444
> Fix claw primitive clause with continuation line (#444) 

- test/claw/directive/call1/reference.f90
- test/claw/directive/call2/reference.f90
- test/claw/sca/sca34/reference_main_cpu.f90
- test/claw/sca/sca34/reference_main_gpu.f90
- test/claw/sca/sca35/reference_main_cpu.f90
- test/claw/sca/sca35/reference_main_gpu.f90
- test/loops/extract6/reference.f90
- test/openacc/array1/reference.f90
**REVIEW**
* Update OMNI Compiler submodule to omni-compiler/xcodeml-tools@2f39735e0c63233531ff971e4f5aaf8f1607117c
> Update OMNI Compiler to 2f39735e0c63233531ff971e4f5aaf8f1607117c

- CHANGELOG.md
- cx2t/src/claw/tatsu/primitive/Pragma.java
- cx2t/src/claw/tatsu/xcodeml/xnode/XnodeUtil.java
- cx2t/src/claw/wani/language/ClawPragma.java
- cx2t/src/claw/wani/language/parser/Claw.g4
- cx2t/src/claw/wani/transformation/ll/loop/LoopHoist.java
- cx2t/unittest/claw/wani/language/language/ClawPragmaTest.java
- test/loops/CMakeLists.txt
- test/loops/hoist10/original_code.f90
- test/loops/hoist10/reference.f90
- test/loops/hoist8/original_code.f90
- test/loops/hoist8/reference.f90
- test/loops/hoist9/original_code.f90
- test/loops/hoist9/reference.f90
**REVIEW**
* `cleanup` clause to remove previous directives in a `loop-hoist` block
Issue #453
> Implementation of cleanup clause for loop-hoisting

- .travis.yml
> Activate sonar in push build on original repo

- CHANGELOG.md
- CMakeLists.txt
- README.md
- cx2t/src/claw/wani/x2t/configuration/Configuration.java
**REVIEW**
* SCA: Initial support of OpenMP 4.5 code generation for accelerator.
* SCA: Smart fusion option as CPU transformation strategy. Tries to group
adjacent statements together.
* `loop-hoist`: new clause `cleanup` to remove previously defined directive.
* Compiler options: `-x=<key:value>` can be used to override configuration
parameters.
* Configuration file version is checked on the major version number.
* OMNI Compiler submodule now pointing to omni-compiler/xcodeml-tools@95e1bf985330ef14cdd0b1afef9c97999e6b6404
> Release v1.1.0

- .travis.yml
- CHANGELOG.md
**REVIEW**
* Update OMNI Compiler submodule to omni-compiler/xcodeml-tools@8d782adcd2fc521911c927540682ce6c0fa620bc
https://github.com/C2SM-RCM/icon-eniac/issues/56
> Update OMNI Compiler to 8d782adcd2fc521911c927540682ce6c0fa620bc

- modules/openacc_lib.f90
- test/openacc/primitive2/reference.f90
**REVIEW**
* Remove `PARAMETER` to avoid reduction by OMNI
> Update OpenACC internal module

- CHANGELOG.md
- test/claw/directive/kcache2/reference.f90
- test/claw/directive/kcache3/reference.f90
- test/claw/directive/kcache4/reference.f90
- test/loops/hoist1/reference.f90
- test/loops/hoist10/reference.f90
- test/loops/hoist2/reference.f90
- test/loops/hoist3/reference.f90
- test/loops/hoist6/reference.f90
- test/loops/hoist7/reference.f90
- test/loops/hoist8/reference.f90
- test/loops/hoist9/reference.f90
**REVIEW**
* Update OMNI Compiler submodule to omni-compiler/xcodeml-tools@4f66174b739fa59d15631a9b55457f809ae70d1f
> Update OMNI Compiler to 4f66174b739fa59d15631a9b55457f809ae70d1f

- cx2t/src/claw/tatsu/primitive/Pragma.java
- test/openacc/continuation/original_code.f90
- test/openacc/continuation/reference.f90
**REVIEW**
* In some cases, some OpenACC directive could disappear
> OpenACC lost directives are now back

- CHANGELOG.md
- CMakeLists.txt
- README.md
**REVIEW**
* Update file for release 1.2.0
> Version 1.2.0

- test/driver/add_paren/original_code.f90
- test/driver/add_paren/reference.f90
**REVIEW**
* Add `--add-paren` test for precedence
> Add precedence test

- driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Split option in automatic dependency resolver
Issue #478
> Allow array splitting in F2X command

- driver/bin/clawfc.in
- driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Debug capability for dependency resolution 
* Activate is by setting env var `CLAW_DEBUG_DEP`
> Add some debugging capability for dependency resolution

- LICENSE
**REVIEW**
* Add MeteoSwiss and ETH Zurich into the copyright
> Add MeteoSwiss and ETH Zurich into the copyright

- cx2t/src/claw/tatsu/primitive/Function.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FfunctionDefinition.java
- cx2t/src/claw/wani/transformation/sca/Sca.java
- cx2t/src/claw/wani/transformation/sca/ScaCPUvectorizeGroup.java
- cx2t/src/claw/wani/transformation/sca/VectorBlock.java
- cx2t/unittest/claw/tatsu/xcodeml/abstraction/AssignStatementTest.java
**REVIEW**
* Detect variable with missing promotion and apply transformation on them
> [SCA/CPU] Detection missing promotion 

- compiler/cray.cmake
**REVIEW**
* Define correct internal macro for Cray FTN
> Define correct internal macro for Cray FTN

- cx2t/src/claw/wani/transformation/ll/loop/LoopHoist.java
- cx2t/src/claw/wani/x2t/translator/ClawTranslator.java
- test/loops/CMakeLists.txt
- test/loops/hoist11/original_code.f90
- test/loops/hoist11/reference.f90
- test/openacc/array6/reference.f90
**REVIEW**
* Allow several nested directive on the same level
> Nested block directives on same level

- LICENSE
**REVIEW**
* 2019 ... one month later
None
> Bump year to 2019

- cx2t/src/claw/tatsu/directive/generator/OpenAcc.java
- cx2t/src/claw/tatsu/xcodeml/xnode/Xname.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/Xcode.java
- cx2t/src/claw/wani/transformation/sca/ScaGPU.java
- test/claw/sca/CMakeLists.txt
- test/claw/sca/sca44/original_code.f90
**REVIEW**
* Raise error when GOTO is used in OpenACC parallel region
Issue #501
> #501: Raise error when GOTO is used in OpenACC parallel region

- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeML.java
- cx2t/src/claw/wani/language/ClawClause.java
- cx2t/src/claw/wani/language/parser/Claw.g4
- cx2t/src/claw/wani/transformation/sca/ScaRoutine.java
- cx2t/src/claw/wani/x2t/translator/ClawTranslator.java
- cx2t/unittest/claw/wani/language/language/ClawPragmaTest.java
- test/claw/sca/CMakeLists.txt
- test/claw/sca/sca45/main.f90
- test/claw/sca/sca45/mo_column.f90
- test/claw/sca/sca45/model.toml
- test/claw/sca/sca45/reference_acc.f90
- test/claw/sca/sca45/reference_cpu.f90
- test/claw/sca/sca45/reference_main_acc.f90
- test/claw/sca/sca45/reference_main_cpu.f90
- test/claw/sca/sca45/reference_main_omp.f90
- test/claw/sca/sca45/reference_omp.f90
**REVIEW**
* `!$claw sca routine` to help transformation of `ELEMENTAL` function.
None
> Introduce SCA routine clause

- cx2t/src/claw/shenron/transformation/DependentTransformationGroup.java
- cx2t/src/claw/shenron/transformation/IndependentTransformationGroup.java
- cx2t/src/claw/shenron/transformation/TransformationGroup.java
- cx2t/src/claw/shenron/translator/AnalyzedPragma.java
- cx2t/src/claw/wani/x2t/translator/ClawTranslatorDriver.java
- cx2t/unittest/build.xml
- cx2t/unittest/claw/shenron/transformation/TransformationAndGroupTest.java
- cx2t/unittest/claw/shenron/translator/AnalyzedPragmaTest.java
**REVIEW**
* Add some unit tests for `claw.shenron`
* Fixes some problem encountered while adding tests.
> Add bunch of tests and fixes in claw.shenron

- cx2t/src/claw/tatsu/primitive/Field.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FbasicType.java
**REVIEW**
* When performing a promotion SCALAR to ARRAY, copy the attributes of the current type.
> FbasicType/promotion: Copy attributes from current type

- cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeProgram.java
**REVIEW**
* Error handling fix
> Avoid expection if parsed document is not readable.

- CHANGELOG.md
- cx2t/src/claw/wani/language/ClawDirective.java
- cx2t/src/claw/wani/language/parser/Claw.g4
- cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java
- cx2t/src/claw/wani/transformation/ll/loop/LoopExtraction.java
- cx2t/src/claw/wani/transformation/ll/loop/LoopInterchange.java
- cx2t/src/claw/wani/x2t/translator/ClawTranslator.java
- cx2t/unittest/claw/wani/language/language/ClawPragmaTest.java
- documentation/developer/code/claw-default.xml
- documentation/developer/code/extension_config.xml
- documentation/manual/claw_fortran_compiler.tex
- driver/etc/claw-default.xml
- driver/etc/claw-low-level-set.xml
- test/loops/fusion10/fusion_first.xml
- test/loops/fusion11/dedicated_config.xml
- test/openacc/array1/original_code.f90
- test/openacc/array10/original_code.f90
- test/openacc/array10/reference.f90
- test/openacc/array2/original_code.f90
- test/openacc/array4/original_code.f90
- test/openacc/array5/original_code.f90
- test/openacc/array6/original_code.f90
- test/openacc/array7/original_code.f90
- test/openacc/array8/original_code.f90
**REVIEW**
* `array-transform` directive became `expand` in specififcation v2.0
> Update grammar array-transform -> expand

- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/directive/generator/OpenAcc.java
- cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java
- cx2t/src/claw/wani/transformation/sca/ScaGPU.java
- test/openacc/array1/original_code.f90
- test/openacc/array1/reference.f90
- test/openacc/array8/original_code.f90
- test/openacc/array8/reference.f90
**REVIEW**
* `parallel` clause of the `expand` directive uses the execution mode strategy from the configuration (`acc_execution_mode`)
> Update generation done by the parallel clause of the expand directive

- cx2t/src/claw/tatsu/directive/common/DataMovement.java
- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/directive/generator/OpenAcc.java
- cx2t/src/claw/tatsu/directive/generator/OpenMp.java
- cx2t/src/claw/wani/language/parser/Claw.g4
- cx2t/src/claw/wani/transformation/sca/ScaForward.java
- cx2t/unittest/claw/wani/language/language/ClawPragmaTest.java
**REVIEW**
* Rename data movement enum to make it clearer
> DataMovement naming

- cx2t/src/claw/wani/transformation/ll/directive/DirectivePrimitive.java
- test/openacc/primitive4/original_code.f90
- test/openacc/primitive4/reference.f90
**REVIEW**
* Avoid multiple `claw` prefix to be kept in the transformed code.
> Primitive directive using CLAW and continuation line symbol

- cx2t/src/claw/tatsu/directive/generator/OpenAcc.java
- cx2t/src/claw/tatsu/primitive/Body.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeML.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/Xnode.java
- cx2t/src/claw/wani/transformation/sca/ScaGPU.java
- test/claw/sca/CMakeLists.txt
- test/claw/sca/sca46/main.f90
- test/claw/sca/sca46/mo_column.f90
- test/claw/sca/sca46/reference_acc.f90
- test/claw/sca/sca46/reference_cpu.f90
- test/claw/sca/sca46/reference_main_acc.f90
- test/claw/sca/sca46/reference_main_cpu.f90
- test/claw/sca/sca46/reference_main_omp.f90
- test/claw/sca/sca46/reference_omp.f90
**REVIEW**
* Transform RETURN statement in IF-THEN-ELSE when possible.
> Handle simple RETURN statement in parallel region

- cx2t/src/claw/wani/transformation/sca/ScaGPU.java
**REVIEW**
* Return value of a function cannot be assumed shape.
> Force assuming shape with function return value

- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/primitive/Field.java
- cx2t/src/claw/tatsu/primitive/Function.java
- cx2t/src/claw/tatsu/primitive/Xmod.java
- cx2t/src/claw/wani/language/parser/Claw.g4
- cx2t/src/claw/wani/transformation/ll/loop/LoopExtraction.java
- cx2t/src/claw/wani/transformation/ll/loop/LoopInterchange.java
- cx2t/src/claw/wani/transformation/sca/ScaCPUvectorizeGroup.java
- cx2t/src/claw/wani/transformation/sca/ScaForward.java
- cx2t/src/claw/wani/transformation/sca/ScaGPU.java
**REVIEW**
* Add `parallel` clause for `sca forward`
> Parallel clause on sca forward

- cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java
**REVIEW**
A few sentences describing the overall goals of the pull request's commits.
Issue #00
Issue #01
> Avoid reaching outside of doStmts size

- cx2t/src/claw/tatsu/primitive/Function.java
- cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java
**REVIEW**
* Adapt SUM call if possible
> Adapt SUM call if possible

- compiler/cray.cmake
> Remove specific cray target

- CHANGELOG.md
- CMakeLists.txt
- README.md
- driver/CMakeLists.txt
- driver/bin/clawfc.in
- driver/etc/claw_f.conf.in
- driver/libexec/claw_f_lib.sh.in
- test/CMakeLists.txt
- test/lib/test.claw_f_lib
**REVIEW**
* Use sha1 sum for tmp file name
> Avoid running into too long name in tmp files + bump to v1.2.2

- cx2t/src/claw/tatsu/xcodeml/backend/OmniBackendDriver.java
**REVIEW**
Propagate error if writing Fortran file fails.
> Propagate error if writing Fortran file fails

- cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeML.java
- cx2t/unittest/claw/tatsu/xcodeml/xnode/fortran/FfunctionTypeTest.java
- documentation/developer/claw_tatsu.tex
- documentation/developer/code/MyFirstTransformation.java
- documentation/developer/guide_claw_tatsu_ast_library.tex
- documentation/developer/guide_configuration.tex
- driver/libexec/claw_f_lib.sh.in
> Some minor modification to documentation + fix dependency solver error

- .gitignore
- .travis.yml
- driver/bin/clawfc.in
- driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Display correct filename instead of hashed file
> Correct filename to report error

- driver/bin/clawfc.in
- driver/libexec/claw_f_lib.sh.in
> Backport fixy for filename

- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/primitive/Condition.java
- cx2t/src/claw/tatsu/primitive/Function.java
- cx2t/src/claw/tatsu/xcodeml/abstraction/AssignStatement.java
- cx2t/src/claw/tatsu/xcodeml/xnode/XnodeUtil.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeML.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/XglobalDeclTable.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/Xnode.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FbasicType.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FfunctionDefinition.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FfunctionType.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FmoduleDefinition.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FortranModule.java
- cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java
- cx2t/src/claw/wani/transformation/ll/utility/ArrayToFctCall.java
- cx2t/src/claw/wani/transformation/sca/VectorBlock.java
- cx2t/unittest/claw/tatsu/xcodeml/xnode/fortran/FmoduleDefinitionTest.java
**REVIEW**
* Adapt code to some new Java 8 features
> Use Java stream in some api calls

- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/primitive/Condition.java
- cx2t/src/claw/tatsu/primitive/Function.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeML.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FfunctionType.java
> Simplify some stream calls

- cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeProgram.java
- driver/bin/clawfc.in
**REVIEW**
* Display filename in error without temp dir
> Display filename in error without temp dir

- cx2t/src/claw/wani/transformation/sca/ScaForward.java
**REVIEW**
* Fix order of directive generation
* JSBACH porting
> Fix order of directive generation

- cx2t/src/claw/tatsu/common/CompilerDirective.java
- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/directive/configuration/AcceleratorDataStrategy.java
- cx2t/src/claw/tatsu/directive/configuration/AcceleratorLocalStrategy.java
- cx2t/src/claw/tatsu/directive/generator/OpenAccExecutionMode.java
- cx2t/src/claw/tatsu/directive/generator/OpenMpExecutionMode.java
- cx2t/src/claw/tatsu/primitive/Condition.java
- cx2t/src/claw/tatsu/primitive/Function.java
- cx2t/src/claw/tatsu/primitive/Xmod.java
- cx2t/src/claw/tatsu/xcodeml/abstraction/AssignStatement.java
- cx2t/src/claw/tatsu/xcodeml/abstraction/FunctionCall.java
- cx2t/src/claw/tatsu/xcodeml/xnode/Xname.java
- cx2t/src/claw/tatsu/xcodeml/xnode/XnodeUtil.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/Xattr.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/Xnode.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FfunctionType.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FmoduleDefinition.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FortranModule.java
- cx2t/src/claw/wani/language/ClawPragma.java
- cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java
- cx2t/src/claw/wani/transformation/sca/Sca.java
- cx2t/src/claw/wani/transformation/sca/ScaCPUvectorizeGroup.java
- cx2t/src/claw/wani/transformation/sca/ScaForward.java
- cx2t/src/claw/wani/transformation/sca/ScaGPU.java
- cx2t/src/claw/wani/x2t/translator/ClawTranslator.java
- cx2t/unittest/claw/tatsu/primitive/LoopTest.java
- cx2t/unittest/claw/tatsu/primitive/PragmaTest.java
- cx2t/unittest/claw/tatsu/xcodeml/xnode/common/XnodeTest.java
- cx2t/unittest/claw/tatsu/xcodeml/xnode/fortran/FmoduleDefinitionTest.java
**REVIEW**
* Some improvements in warnings and debug messages
* Add FunctionCall abstraction
* Propagate information about ELEMENTAL in the CLAW.XMOD file
> Improvement for SCA/ELEMENTAL support

- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/primitive/Field.java
- cx2t/src/claw/tatsu/primitive/Function.java
- cx2t/src/claw/tatsu/primitive/Loop.java
- cx2t/src/claw/tatsu/primitive/Xmod.java
- cx2t/src/claw/tatsu/xcodeml/abstraction/FunctionCall.java
- cx2t/src/claw/tatsu/xcodeml/backend/OmniBackendDriver.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeML.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/Xid.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/Xnode.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FfunctionDefinition.java
- cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FortranModule.java
- cx2t/src/claw/wani/transformation/ll/loop/LoopExtraction.java
- cx2t/src/claw/wani/transformation/ll/utility/ArrayToFctCall.java
- cx2t/src/claw/wani/transformation/sca/Sca.java
- cx2t/src/claw/wani/transformation/sca/ScaCPUvectorizeGroup.java
- cx2t/src/claw/wani/x2t/translator/ClawTranslatorDriver.java
- cx2t/unittest/claw/tatsu/primitive/FieldTest.java
- cx2t/unittest/claw/tatsu/xcodeml/xnode/common/XnodeTest.java
- driver/bin/clawfc.in
* Introduce call chaining in Xnode methods that permit it. 
* More use of `FunctionCall` abstraction
> Some code cleanup + abstraction

- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/primitive/Xmod.java
- cx2t/src/claw/tatsu/xcodeml/abstraction/FunctionCall.java
- cx2t/src/claw/tatsu/xcodeml/xnode/XnodeUtil.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeML.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/Xnode.java
- cx2t/src/claw/wani/language/ClawClause.java
- cx2t/src/claw/wani/language/ClawPragma.java
- cx2t/src/claw/wani/language/parser/Claw.g4
- cx2t/src/claw/wani/serialization/Serialization.java
- cx2t/src/claw/wani/serialization/SerializationMode.java
- cx2t/src/claw/wani/serialization/SerializationStep.java
- cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java
- cx2t/src/claw/wani/transformation/sca/ScaForward.java
- cx2t/src/claw/wani/transformation/sca/ScaGPU.java
- cx2t/src/claw/wani/x2t/configuration/Configuration.java
- cx2t/unittest/claw/tatsu/xcodeml/xnode/common/XnodeTest.java
- cx2t/unittest/claw/tatsu/xcodeml/xnode/common/XnodeUtilTest.java
- cx2t/unittest/claw/wani/language/language/ClawPragmaTest.java
- driver/etc/claw-default.xml
* Ability to generate serialization calls for Serialbox2 around `sca foward` directives
None
> Add serialbox2 serialization support in SCA FORWARD and EXPAND

- cx2t/src/claw/tatsu/directive/common/Directive.java
- cx2t/src/claw/tatsu/xcodeml/abstraction/Xblock.java
- cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java
- cx2t/src/claw/wani/transformation/sca/ScaForward.java
- cx2t/src/claw/wani/transformation/sca/ScaGPU.java
- test/openacc/array1/reference.f90
- test/openacc/array8/reference.f90
> Add block abstraction to handle data/parallel region correctly

- cx2t/src/claw/tatsu/xcodeml/abstraction/FunctionCall.java
- cx2t/src/claw/wani/serialization/Serialization.java
- cx2t/src/claw/wani/transformation/sca/ScaForward.java
> Additional fixes for SCA elemental

- cx2t/src/claw/wani/transformation/sca/Sca.java
**REVIEW**
A few sentences describing the overall goals of the pull request's commits.
> Fix layout retrieval

- cx2t/src/claw/tatsu/xcodeml/xnode/common/Xnode.java
**REVIEW**
- Better representation
> Add binary operator representation ability

- cx2t/src/claw/tatsu/primitive/Type.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeML.java
**REVIEW**
* Dimensions can now be defined with minus, plus, div and mul expression.
> Remove some restriction in array dimension specification inside SCA

- cx2t/src/claw/wani/transformation/sca/ScaRoutine.java
**REVIEW**
* Let `sca routine` to be in subroutine/function that are not elemental
> Allow the directive also in none elemental.

- CHANGELOG.md
**REVIEW**
* Update OMNI Compiler submodule to omni-compiler/xcodeml-tools@772cf79077ac5f04cfc204fc7e0b53755a362d8b
> Update OMNI Compiler to 772cf79077ac5f04cfc204fc7e0b53755a362d8b

- CMakeLists.txt
**REVIEW**
* OMNI Compiler submodule compilation with 1 single thread
> Try to force OMNI Compiler with 1 thread as it is not safe

- driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Fix a problem of module use detection
> Match exact module name

- driver/libexec/claw_f_lib.sh.in
> Enhance debugging output for dependency resolver

- driver/etc/claw-default.xml
**REVIEW**
* Disable option by default
> Serialization off by default

- cx2t/src/claw/wani/serialization/Serialization.java
**REVIEW**
* Do not insert modules uses when serialization is disable.
> Fix serialization transformation

- cx2t/src/claw/wani/serialization/Serialization.java
> Quick fix on serialization support

- cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java
- cx2t/src/claw/wani/transformation/sca/ScaForward.java
- cx2t/src/claw/wani/x2t/configuration/Configuration.java
- driver/etc/claw-default.xml
**REVIEW**
* New option to disable update generated by `update` clause
> Add option to disable sca forward update globally

- cx2t/src/claw/wani/serialization/Serialization.java
- cx2t/src/claw/wani/transformation/sca/ScaForward.java
- cx2t/src/claw/wani/x2t/configuration/Configuration.java
- driver/etc/claw-default.xml
**REVIEW**
A few sentences describing the overall goals of the pull request's commits.
Issue #00
Issue #01
> Add different options to serialisation

- CHANGELOG.md
- CMakeLists.txt
- README.md
**REVIEW**
* Preparation for 2.0.1
> Release 2.0.1

- cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java
**REVIEW**
Issue #00
Issue #01
> Update missing switch

- cx2t/src/claw/tatsu/primitive/Field.java
- cx2t/src/claw/tatsu/xcodeml/xnode/common/Xnode.java
- cx2t/src/claw/wani/transformation/sca/Sca.java
- cx2t/src/claw/wani/transformation/sca/ScaCPUvectorizeGroup.java
- cx2t/src/claw/wani/transformation/sca/ScaForward.java
- cx2t/src/claw/wani/transformation/sca/ScaGPU.java
- test/claw/sca/CMakeLists.txt
- test/claw/sca/sca23/reference_acc.f90
- test/claw/sca/sca23/reference_omp.f90
- test/claw/sca/sca24/reference_acc.f90
- test/claw/sca/sca24/reference_omp.f90
- test/claw/sca/sca47/main.f90
- test/claw/sca/sca47/mo_column.f90
- test/claw/sca/sca47/reference_acc.f90
- test/claw/sca/sca47/reference_cpu.f90
- test/claw/sca/sca47/reference_main_acc.f90
- test/claw/sca/sca47/reference_main_cpu.f90
- test/claw/sca/sca47/reference_main_omp.f90
- test/claw/sca/sca47/reference_omp.f90
**REVIEW**
Fix #578 
Issue #578
> Fix 578: Adapt array reference looking like scalar

- .travis.yml
- driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Update Travis CI dist to xenial
> Remove cabal dependencies

- CHANGELOG.md
- CMakeLists.txt
- README.md
**REVIEW**
Incremented CLAW compiler version and  updated change log.
> Preparation for release 2.0.2

- driver/libexec/claw_f_lib.sh.in
**REVIEW**
Makes CLAW driver print debug output and exit on OMNI failure.
> Made CLAW stop on OMNI F_Front failure

- CHANGELOG.md
- README.md
- sonar-project.properties
**REVIEW**
Updated release notes and version.
> Release 2.1

- driver/src/clawfc/Build.java
- driver/src/clawfc/Driver.java
- driver/src/clawfc/Options.java
- driver/tests/res/xmod_generation/explicit_targets/input/inc/dep.f90
- driver/tests/res/xmod_generation/explicit_targets/input/m.f90
- driver/tests/res/xmod_generation/explicit_targets/reference/dep_mod.xmod
- driver/tests/res/xmod_generation/explicit_targets/reference/mod1.xmod
- driver/tests/res/xmod_generation/explicit_targets/reference/mod2.xmod
- driver/tests/res/xmod_generation/explicit_targets/reference/not_target_mod.xmod
- driver/tests/src/clawfc/tests/XmodGenerationTest.java
**REVIEW**
Optional list of target modules can now be added to CLI option --gen-mod-files.
> Added optional list of modules to --gen-mod-files
