omni-cx2x/src/cx2x/translator/language/helper/accelerator/AcceleratorGenerator.java, omni-cx2x/src/cx2x/translator/language/helper/accelerator/AcceleratorHelper.java, omni-cx2x/src/cx2x/translator/language/helper/accelerator/AcceleratorNone.java, omni-cx2x/src/cx2x/translator/language/helper/accelerator/OpenAcc.java, omni-cx2x/src/cx2x/translator/language/helper/accelerator/OpenMp.java
Adapt the `AcceleratorGenerator` to be able to generate directives for OpenMP 4.5. This means essentially to be able to generate 1 to n directive for a single call to `AcceleratorGenerator` methods.
Currently, this is fixed.
=> AcceleratorGenerator architecture suitable for OpenMP/CPU and OpenMP 4.5/GPU

omni-cx2x/src/cx2x/translator/common/analysis/dependence/DependenceAnalysis.java, omni-cx2x/src/cx2x/translator/common/analysis/dependence/DependenceDirection.java, omni-cx2x/src/cx2x/translator/common/analysis/dependence/IterationSpace.java, omni-cx2x/src/cx2x/xcodeml/xnode/Xnode.java, omni-cx2x/unittest/cx2x/translator/common/analysis/dependence/DependenceAnalysisTest.java, omni-cx2x/unittest/cx2x/translator/common/analysis/dependence/IterationSpace.java, omni-cx2x/unittest/data/loop_dependence.xml, omni-cx2x/unittest/data/loop_dependence3d.xml, omni-cx2x/unittest/helper/TestConstant.java.in
Currently, the loops inside a parallelized subroutine are safely annotated with an `!$acc loop seq` directive in order to ensure a correct result. Some of those loops, have no dependency and could be parallelized some more. The `DependenceAnalysis` class introduces some basic dependency analysis ability to decide which directive should be generated.
See issue: #83
=> Iteration space dependency analysis class

compiler/cray.cmake
Cray enable OpenMP by default and it causes problem when using FPP in CLAW driver for GPU traget
=> Fix FPP for Cray and OpenMP

omni-cx2x/src/cx2x/translator/ClawXcodeMlTranslator.java, omni-cx2x/src/cx2x/translator/language/base/ClawLanguage.java, omni-cx2x/src/cx2x/translator/language/common/ClawConstraint.java, omni-cx2x/src/cx2x/translator/language/parser/Claw.g4, omni-cx2x/src/cx2x/translator/transformation/ClawTransformation.java, omni-cx2x/src/cx2x/translator/transformation/claw/ArrayToFctCall.java, omni-cx2x/src/cx2x/translator/transformation/claw/Kcaching.java, omni-cx2x/src/cx2x/translator/transformation/claw/parallelize/Parallelize.java, omni-cx2x/src/cx2x/translator/transformation/claw/parallelize/ParallelizeForward.java, omni-cx2x/src/cx2x/translator/transformation/loop/ArrayTransform.java, omni-cx2x/src/cx2x/translator/transformation/loop/LoopExtraction.java, omni-cx2x/src/cx2x/translator/transformation/loop/LoopFusion.java, omni-cx2x/src/cx2x/translator/transformation/loop/LoopHoist.java, omni-cx2x/src/cx2x/translator/transformation/loop/LoopInterchange.java, omni-cx2x/src/cx2x/translator/transformation/openacc/DirectivePrimitive.java, omni-cx2x/src/cx2x/translator/transformation/openacc/OpenAccContinuation.java, omni-cx2x/src/cx2x/translator/transformation/utility/UtilityRemove.java, omni-cx2x/src/cx2x/translator/transformation/utility/XcodeMLWorkaround.java, omni-cx2x/src/cx2x/xcodeml/error/XanalysisError.java, omni-cx2x/src/cx2x/xcodeml/transformation/DependentTransformationGroup.java, omni-cx2x/src/cx2x/xcodeml/transformation/Transformation.java, omni-cx2x/src/cx2x/xcodeml/xnode/XcodeProgram.java, omni-cx2x/unittest/cx2x/translator/language/ClawLanguageTest.java, test/loops/CMakeLists.txt, test/loops/fusion10/CMakeLists.txt, test/loops/fusion10/original_code.f90, test/loops/fusion10/reference.f90, test/loops/fusion9/CMakeLists.txt, test/loops/fusion9/original_code.f90, test/loops/fusion9/reference.f90
- Allow constraint clause for the loop-fusion directive
- Release the direct sibling constraint for a loop-fusion transformation where both directive are set to `constraint(none)`
- Allow `loop-hoist` to work with nested `DO` in `DO`
Related to feature request by Huadong (ECMWF) #121 & #122 
Related test case: 
- `test/loops/fusion9`
- `test/loops/fusion10`
- `test/loops/hoist4`
=> Implements constraint clause for loop-fusion directive + more flexiblity in loop-hoist

.travis.yml, scripts/run.shellcheck.sh
- Exit script when errors are detected
- Add correct shellcheck version to CI
=> Exit correctly run.shellcheck.sh in case of error

driver/bin/clawfc.in
Cray compiler is not able to redirect the preprocessor output to a file directly. Therefore we need a special case. As the preprocess pass in not in the full piped workflow, the restriction doesn't apply yet.
=> Remove restriction for Cray

.travis.yml, cx2t/src/claw/tatsu/primitive/Condition.java, cx2t/src/claw/tatsu/primitive/Function.java, cx2t/src/claw/tatsu/xcodeml/abstraction/AssignStatement.java, cx2t/src/claw/tatsu/xcodeml/xnode/common/Xnode.java, cx2t/src/claw/wani/transformation/sca/Parallelize.java, cx2t/src/claw/wani/transformation/sca/ParallelizeForward.java, cx2t/unittest/claw/tatsu/primitive/ConditionTest.java, cx2t/unittest/claw/tatsu/xcodeml/abstraction/AssignStatementTest.java, cx2t/unittest/claw/tatsu/xcodeml/xnode/common/XnodeTest.java, cx2t/unittest/data/assignStatement.xml, cx2t/unittest/data/assignStatement2.xml, cx2t/unittest/helper/TestConstant.java.in, driver/bin/clawfc.in, driver/libexec/claw_f_lib.sh.in, test/claw/abstraction/CMakeLists.txt, test/claw/abstraction/abstraction34/main.f90, test/claw/abstraction/abstraction34/mo_column.f90, test/claw/abstraction/abstraction34/reference_cpu.f90, test/claw/abstraction/abstraction34/reference_gpu.f90, test/claw/abstraction/abstraction34/reference_main_cpu.f90, test/claw/abstraction/abstraction34/reference_main_gpu.f90, test/claw/abstraction/abstraction35/main.f90, test/claw/abstraction/abstraction35/mo_column.f90, test/claw/abstraction/abstraction35/reference_cpu.f90, test/claw/abstraction/abstraction35/reference_gpu.f90, test/claw/abstraction/abstraction35/reference_main_cpu.f90, test/claw/abstraction/abstraction35/reference_main_gpu.f90
**REVIEW**
* Issue #355 shows a bug in the CPU target transformation for SCA code. In this PR, we are trying new methods to categorize the assignment statement before inserting `DO` statement. Categorization will allow us to decide in a better way where to place the `DO` statement.
Issue #355
=> Categorization of assignment statement

driver/libexec/claw_f_lib.sh.in
**REVIEW**
* In some special cases, the dependency solver could be stuck in infinite recursion. This PR avoid this behavior.
=> Avoid infinite recursion if dependency cycle

cx2t/src/claw/wani/transformation/sca/Parallelize.java
**REVIEW**
* Avoid double array reference adaptation in indirect promotion
=> Set promotion flag to ref adapted

driver/bin/clawfc.in
**REVIEW**
* Generate the temp directory using `mktemp` instead of `__omni_tmp_PID` to avoid potentital collision.
=> Use mktemp to create the temp dir

.gitmodules, cx2t/claw.properties, cx2t/src/build.xml, cx2t/unittest/build.xml, properties.cmake
**REVIEW**
* OMNI Compiler base repository will not contain front-end and back-end anymore. These will be moved to `xcodeml-tools` submodule repository.
=> Switch from omni-compiler to xcodeml-tools repository

driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Switch to other method if `mapfile` is not available like on OS X
=> Fix problem on OS X with missing mapfile command

cx2t/src/claw/ClawX2T.java, cx2t/src/claw/tatsu/common/Context.java, cx2t/src/claw/wani/x2t/translator/ClawTranslatorDriver.java
**REVIEW**
* Combination of OpenMP fine grain directive generation + CPU target is known to give poor performance. Therefore, a warning is issued when user use this combination.
Issue #422
=>  Add warning for OpenMP/CPU usage

cx2t/src/claw/wani/transformation/sca/Parallelize.java, test/claw/sca/CMakeLists.txt, test/claw/sca/sca38/main.f90, test/claw/sca/sca38/mo_column.f90, test/claw/sca/sca38/reference_cpu.f90, test/claw/sca/sca38/reference_main_cpu.f90
**DISCUSSION**
This PR adds a test for handling nested conditionals to the new SCA-CPU "smart fusion" branch. 
It also provides a small bug fix for cases where nested `IF` nodes would cause double wrapping of a code block, as illustrated in the second code block in the included test (`sca38`). This one is easily fixed by changing the corresponding lookup in `wani.transformation.sca.Parallelize.transformFusionForCPUGather()`.
The new test also highlights a more complex bug, where again double-wrapping is triggered by nested `IF`/`LOOP` combinations (the last block in the new test). The problem is basically this:
```
IF (flag1) THEN
z(k) = ...<depends only on k>
DO j=1, 5 
IF (flag2) THEN
z(k) = ...<depends on k, j>
END IF
END DO
END IF
```
The problem, as far as I can see it, is that the …
=> [SCA] CPU-smart-fusion: Additional test and bugfix for nested conditionals

cx2t/src/claw/ClawX2T.java, driver/bin/clawfc.in, driver/libexec/claw_f_lib.sh.in, test/driver/CMakeLists.txt, test/driver/add_paren/original_code.f90, test/driver/add_paren/reference.f90
**REVIEW**
* New option `--add-paren` allows to force parenthesis in mathematical binary operations.
=> Add parenthesis option from backend driven from driver

README.md, driver/libexec/claw_f_lib.sh.in, test/driver/CMakeLists.txt, test/driver/dependencies1/mod2.f90, test/driver/dependencies1/original_code.f90, test/driver/dependencies1/reference.f90
**REVIEW**
* Pass args with splitting to the preprocessor
Issue #478
=> Fix #478: Pass correctly arguments to dependency resolver

driver/bin/clawfc.in, driver/libexec/claw_f_lib.sh.in
**REVIEW**
* `--debug-ffront` will drive OMNI Fortran front-end in debug mode
=> Add option to drive OMNI F_Front debug

driver/bin/clawfc.in
**REVIEW**
* When using piped workflow, redirect only when `-o` is provided on the command line
Issue #498
=> Fix #498: Redirect to file only if -o is provided

cx2t/src/claw/tatsu/primitive/Field.java, cx2t/src/claw/tatsu/primitive/Loop.java, cx2t/src/claw/tatsu/primitive/Type.java, cx2t/src/claw/tatsu/primitive/Xmod.java, cx2t/src/claw/tatsu/xcodeml/abstraction/NestedDoStatement.java, cx2t/src/claw/tatsu/xcodeml/abstraction/PromotionInfo.java, cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeML.java, cx2t/src/claw/tatsu/xcodeml/xnode/common/Xnode.java, cx2t/src/claw/wani/transformation/sca/Sca.java, cx2t/src/claw/wani/transformation/sca/ScaForward.java, cx2t/src/claw/wani/transformation/sca/ScaGPU.java, cx2t/src/claw/wani/x2t/configuration/Configuration.java, cx2t/unittest/claw/tatsu/primitive/FieldTest.java, driver/etc/claw-default.xml, driver/libexec/claw_f_lib.sh.in, test/claw/sca/CMakeLists.txt
* Additional configuration for SCA transformation applied in ELEMENTAL function/subroutine. Sometimes, it is easier to use assumed shaped array and not insert new parameters for the lower bound/upper bound in the function/subroutine signature. This works only for subroutine or function in which the return value is not promoted. Return value cannot have a deferred shape. 
None
=> [SCA] Force promotion with assumed shape array when possible in ELEMENTAL function/subroutine

cx2t/src/claw/tatsu/common/Message.java, cx2t/src/claw/tatsu/primitive/Xmod.java, cx2t/src/claw/tatsu/xcodeml/xnode/Xname.java, cx2t/src/claw/tatsu/xcodeml/xnode/XnodeUtil.java, cx2t/src/claw/tatsu/xcodeml/xnode/common/Xattr.java, cx2t/src/claw/tatsu/xcodeml/xnode/common/XcodeML.java, cx2t/src/claw/tatsu/xcodeml/xnode/common/Xnode.java, cx2t/src/claw/tatsu/xcodeml/xnode/fortran/FfunctionType.java, cx2t/src/claw/wani/transformation/sca/Sca.java, cx2t/src/claw/wani/transformation/sca/ScaForward.java, cx2t/src/claw/wani/transformation/sca/ScaGPU.java, cx2t/src/claw/wani/transformation/sca/ScaRoutine.java, cx2t/unittest/claw/tatsu/xcodeml/xnode/common/XnodeUtilTest.java, driver/libexec/claw_f_lib.sh.in, test/claw/sca/sca41/reference_main_acc.f90, test/claw/sca/sca41/reference_main_omp.f90, test/claw/sca/sca43/reference_main_acc.f90, test/claw/sca/sca43/reference_main_omp.f90, test/claw/sca/sca45/reference_main_acc.f90, test/claw/sca/sca45/reference_main_omp.f90
**REVIEW**
* When `sca_elemental_promotion_assumed` is used, forward should not add any argument to fit/sub call. 
* Handle return value in `create` and `update` clauses.
=> Adaptation of SCA forward clause for ELEMENTAL

CHANGELOG.md, CMakeLists.txt, README.md, driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Fix cray preprocessor filename in dependency resolver
* Bump to version 1.2.3
=> Fix cray preprocessor filename in dependency resolver

driver/libexec/claw_f_lib.sh.in
In the `process_dependencies` function we may end up in infinite recursive calls if the requested dependency doesn't exist and if there is a module that is a substring of the requested dependency.
To illustrate the issue, let's  assume that :
- a module `io_utilities` depends on the module `netcdf`;
- the module `netcdf` doesn't exist in the current project or path;
- there is a module `netcdf_io` which dependent on `io_utilities`;
in that case, the current grep construction:
```
found_file=("$(grep -s -l -i "^ *MODULE *${module_name}" \
"${directory}"/*"${ext}" | grep -v ".*\\.claw\\..*")")
```
will match `netcdf_io` and thus start to loop in an non-existent circular dependency, ending up in infinite recursive calls.
The solution is to force a MODULE match until the end of the string …
=> Improve grep module regexp to avoid partial match

CHANGELOG.md, CMakeLists.txt, README.md, cx2t/src/claw/tatsu/directive/generator/OpenMp.java, cx2t/src/claw/tatsu/primitive/Field.java, cx2t/src/claw/tatsu/xcodeml/abstraction/Xblock.java, cx2t/src/claw/wani/transformation/ll/loop/ExpandNotation.java, cx2t/unittest/claw/wani/language/language/ClawPragmaTest.java, documentation/developer/code/claw-default.xml, documentation/developer/code/extension_config.xml, documentation/developer/code/external_config.xml, documentation/developer/guide_claw_shenron.tex, documentation/manual/claw_fortran_compiler.tex, driver/etc/claw-default.xml, test/claw/sca/sca32/promote.xml, test/claw/sca/sca33/enable_collapse.xml, test/driver/external1/external_config.xml, test/loops/fusion10/fusion_first.xml, test/loops/fusion11/dedicated_config.xml
* `array-transform` directive as been renamed `expand` as specified in v2.0 of
the CLAW Directive Language Specification.
* `parallel` clause for `expand` directive is implemented.
* `update` clause for `expand` directive is implemented.
* beta serialization support for `expand` and `sca` elemental directives.
* SCA: support for transformation in ELEMENTAL function/subroutine for
GPU target
* low-level: block directive like `loop-hoist` can now be nested on the same
depth.
* driver: `_CRAYFTN` macro is passed directly when Cray preprocessor is used.
* `array-transform` directive as been renamed `expand` as specified in v2.0 of
the CLAW Directive Language Specification.
* `parallel` clause for `expand` directive is implemented.
* OMNI Compiler submodule now pointing to …
=> Preparation for release 2.0

driver/bin/clawfc.in, driver/libexec/claw_f_lib.sh.in
**REVIEW**
* Add option `--no-module-cache` to deactivate the front-end module cache from clawfc
=> clawfc option --no-module-cache

driver/libexec/claw_f_lib.sh.in
**REVIEW**
If a source file is provided as input to `clawfc`, it undergoes an additional preprocessing step `claw::applyPreprocessorPass`. However, if a file is an implicit input (i.e. `clawfc` parses it in order to generate a module file for the main input), this step is missing, which leads to problems with some Fortran preprocessors (e.g. `gfortran`). Hopefully, this PR fixes that.
Didn't find any.
=> Run claw::applyPreprocessorPass also when processing dependencies

CMakeLists.txt
The compilation of the omnicompiler uses a c99 compiler. The possibility to use the CMAKE_C_FLAGS in order to set the "-stc=c99" would be therefore useful in case one does not use a c99 compiler by default. The variable is then passed to the omnicompiler Autotools file via the CFLAGS=${CMAKE_C_FLAGS} command added to the main CMake file.
Issue #00 
Issue #01 
[100%] Performing build step for 'omni-compiler'
Created c-exprcode.h, c-exprcode.c
updating c-parser.h
updating c-parser.output
Created c-token.c, c-token.h
c-expr.c: In function ‘innerFreeExprOfBinaryNode’:
c-expr.c:2168:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
for(int i = 0; i < 2; ++i)
^
c-expr.c:2168:5: note: use option -std=c99 or -std=gnu99 to compile your code
=> ADD: possibility to use CMAKE_C_FLAGS=" "

cx2t/src/claw/tatsu/primitive/Field.java, cx2t/src/claw/tatsu/primitive/Type.java, cx2t/src/claw/tatsu/xcodeml/abstraction/DimensionDefinition.java, cx2t/src/claw/tatsu/xcodeml/abstraction/NestedDoStatement.java, cx2t/src/claw/wani/transformation/sca/Sca.java, cx2t/unittest/claw/tatsu/primitive/LoopTest.java, cx2t/unittest/claw/tatsu/xcodeml/abstraction/DimensionTest.java, test/claw/sca/CMakeLists.txt, test/claw/sca/iteration_size_model.toml, test/claw/sca/sca48/main.f90, test/claw/sca/sca48/mo_column.f90, test/claw/sca/sca48/reference_acc.f90, test/claw/sca/sca48/reference_cpu.f90, test/claw/sca/sca48/reference_main_acc.f90, test/claw/sca/sca48/reference_main_cpu.f90, test/claw/sca/sca48/reference_main_omp.f90, test/claw/sca/sca48/reference_omp.f90
**REVIEW**
When using the new `!$claw model data` API for marking promotion variables in combination with a model-config file, the insertion of new loops in the CPU and GPU backends ignores any explicitly provided `[dimensions.iteration]` variables. This PR fixes this and adds a new test to demonstrate the correct insert of CPU and GPU loops over iteration ranges that are different to the provided size variables. In this test the loops inserted iteration over the range `DO p = pstart , pend, 1`, while the promoted variable dimension is `t ( 1 : nproma, nz)`.
=> Fix for iterations space with automated model-data promotion

cx2t/src/claw/tatsu/directive/common/Directive.java, test/claw/sca/CMakeLists.txt, test/claw/sca/sca49/original_code.f90, test/claw/sca/sca49/reference.f90
**REVIEW**
Fix #598. `findParallelRegionStart` and `findParallelRegionEnd` are used to determine the start and end insertion point for the DO statement. These functions were returning null if the directive was set to none. 
Issue #598
=> [sca] Fix issue #598

driver/libexec/claw_f_lib.sh.in
**REVIEW**
This fixes a bug introduced in #579.
Note, however, that the problem described in https://github.com/omni-compiler/xcodeml-tools/issues/165 is also the case of the Cray Fortran preprocessor. We could fix that with an additional preprocessing step, i.e. we could replace
```fortran
integer b ; &
&integer c
integer d ;&
&integer e
integer f ;&
integer g
```
with
```fortran
integer b 
integer c
integer d 
integer e
integer f 
integer g
```
=> Fix the dependency preprocessing for Cray compiler
